language: bash
services: docker

env:
  global:
    - IMAGE_NAME=kcollins/xvfb
  matrix:
    - VERSION=latest

before_script:
  - FULL_IMAGE="$IMAGE_NAME:$VERSION"

script:
  - travis_retry docker build -t "$FULL_IMAGE" .

after_script:
  - docker images

before_deploy:
  - echo $HUB_PASSWORD | docker login -u "$HUB_LOGIN" --password-stdin

deploy:
  provider: script
  script: docker push "$FULL_IMAGE"
  on:
    branch: master
